import { type BuiltinLanguage, type BuiltinTheme, createHighlighter, type Highlighter } from 'shiki';

export const shikiEnabledThemes: BuiltinTheme[] = [
  'catppuccin-frappe',
  'catppuccin-latte',
  'catppuccin-macchiato',
  'catppuccin-mocha',
  'dark-plus',
  'github-dark',
  'github-dark-default',
  'github-dark-dimmed',
  'github-dark-high-contrast',
  'github-light',
  'github-light-default',
  'github-light-high-contrast',
  'laserwave',
  'light-plus',
  'material-theme-darker',
  'material-theme-lighter',
  'material-theme-ocean',
  'material-theme-palenight',
  'monokai',
  'night-owl',
  'nord',
  'one-dark-pro',
  'one-light',
  'solarized-dark',
  'solarized-light',
  'synthwave-84',
  'tokyo-night',
  'vesper',
  'vitesse-black',
  'vitesse-dark',
  'vitesse-light',
];

export const shikiEnabledLanguages: BuiltinLanguage[] = [
  'angular-html',
  'angular-ts',
  'apache',
  'asm',
  'astro',
  'bat',
  'c',
  'clj',
  'cmake',
  'codeowners',
  'ql',
  'lisp',
  'cpp',
  'cs',
  'css',
  'csv',
  'cql',
  'dart',
  'diff',
  'docker',
  'dotenv',
  'fish',
  'f',
  'fs',
  'go',
  'gql',
  'haml',
  'hs',
  'html',
  'imba',
  'ini',
  'java',
  'js',
  'json',
  'json5',
  'jsonc',
  'jsonl',
  'jsx',
  'jl',
  'kt',
  'latex',
  'less',
  'llvm',
  'log',
  'lua',
  'make',
  'md',
  'matlab',
  'mdc',
  'mdx',
  'mmd',
  'mips',
  'nf',
  'nginx',
  'nix',
  'nu',
  'objc',
  'ocaml',
  'pascal',
  'perl',
  'php',
  'postcss',
  'ps',
  'prisma',
  'proto',
  'pug',
  'py',
  'reg',
  'regex',
  'rb',
  'rs',
  'sass',
  'scala',
  'scheme',
  'scss',
  'sh',
  'shellsession',
  'sql',
  'ssh-config',
  'styl',
  'svelte',
  'tex',
  'toml',
  'lit',
  'ts',
  'tsx',
  'tsp',
  'typ',
  'vb',
  'vim',
  'vue',
  'vue-html',
  'wasm',
  'wenyan',
  'wiki',
  'xml',
  'yaml',
  'zig',
];

declare global {
  // eslint-disable-next-line vars-on-top
  var __SHIKI_HIGHLIGHTER_MEMO__: Highlighter | undefined;
}

export const createMemorizedHighlighter = async () => {
  globalThis.__SHIKI_HIGHLIGHTER_MEMO__ ||= await createHighlighter({
    themes: shikiEnabledThemes,
    langs: shikiEnabledLanguages,
  });

  return globalThis.__SHIKI_HIGHLIGHTER_MEMO__;
};
